/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronahospital.gui;

import coronahospital.dao.ChannelDao;
import coronahospital.dao.DoctorDao;
import coronahospital.dao.PatientDao;
import coronahospital.dto.ChannelDTO;
import coronahospital.dto.DoctorDTO;
import coronahospital.dto.PatientDTO;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SUDHANSHU YADAV
 */
public class ChannelRegistration extends javax.swing.JFrame {

    /**
     * Creates new form Patient
     */
    private static String username;
    private  static String patientno;
    private static String doctorno;
    private static String room;
    private static String channelId;
    private static int logid;
    private static String date;
    public ChannelRegistration() {
        initComponents();
    }
    public ChannelRegistration(String uname,int logid)
    {
        initComponents();//used to initiallise the form
        username=uname;
        lblusername.setText(username.toUpperCase());
        autoid();
        doctorList();
        patientList();
        channelShow();
    }
    public void doctorList()
    {
       
        try {
            ArrayList<DoctorDTO> al;
            al = DoctorDao.doctorShowList();
            if(al.isEmpty())
       {
           JOptionPane.showMessageDialog(null,"there is no doctor to show in list....");
       }
       else{
        doctorname.removeAll();
        for(DoctorDTO d:al)
        {
            doctorname.addItem(d.getName());
        }
        }
        }catch (SQLException ex) {
            Logger.getLogger(ChannelRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
     }
     public void patientList() 
    {
        try {
            ArrayList<PatientDTO> al=PatientDao.patientShowList();
            if(al.isEmpty())
            {
              JOptionPane.showMessageDialog(null,"there is no patient to show in list....");
             }
            else{
               jComboBox1.removeAll();
               for(PatientDTO p:al)
                {
                   jComboBox1.addItem(p.getName());
                  }
             }
                }
        catch (SQLException ex)
           {
              Logger.getLogger(ChannelRegistration.class.getName()).log(Level.SEVERE, null, ex);
             }
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblchannelno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        doctorname = new javax.swing.JComboBox();
        roomno = new javax.swing.JSpinner();
        datechoose = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        clearallbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        channeltable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Channel Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 204, 204))); // NOI18N

        lblchannelno.setBackground(new java.awt.Color(255, 255, 255));
        lblchannelno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblchannelno.setForeground(new java.awt.Color(0, 255, 204));
        lblchannelno.setText("channelno");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CHANNEL NO.");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DOCTOR NAME");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PATIENT NAME");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATE");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ROOM NO");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(lblchannelno, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datechoose, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doctorname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomno))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblchannelno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(doctorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(roomno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(datechoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 204));
        jLabel1.setText("CHANNEL REGISTRATION");

        addbtn.setBackground(new java.awt.Color(0, 255, 153));
        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(102, 255, 255));
        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        clearallbtn.setBackground(new java.awt.Color(204, 204, 204));
        clearallbtn.setText("CLEARALL");
        clearallbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearallbtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(255, 153, 153));
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setText("LOGOUT");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        lblusername.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblusername.setForeground(new java.awt.Color(204, 255, 255));
        lblusername.setText("USERNAME");

        channeltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Channelno", "DocName", "Patient Name", "Room No", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        channeltable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channeltableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(channeltable);

        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\SUDHANSHU YADAV\\Documents\\NetBeansProjects\\CoronaHospital\\src\\Images\\download.png")); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblusername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(addbtn)
                                .addGap(18, 18, 18)
                                .addComponent(updatebtn)
                                .addGap(18, 18, 18)
                                .addComponent(deletebtn)
                                .addGap(18, 18, 18)
                                .addComponent(clearallbtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblusername)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addbtn)
                            .addComponent(updatebtn)
                            .addComponent(deletebtn)
                            .addComponent(clearallbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Login l=new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:

        String chid=lblchannelno.getText();
        boolean status;
        try {
            status = ChannelDao.deleteChannel(chid);
            if(status)
            {
                JOptionPane.showMessageDialog(null,"Record delete...","Congrats!!",JOptionPane.INFORMATION_MESSAGE);
                clearAll();
                autoid();
                channelShow();
                addbtn.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChannelRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_deletebtnActionPerformed

    private void clearallbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearallbtnActionPerformed
        // TODO add your handling code here:
        clearAll();
      //  autoid();
        channelShow();
       // patientShow();
        //DefaultTableModel df=(DefaultTableModel)patienttable.getModel();

        // set
    }//GEN-LAST:event_clearallbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
      
        try {
          ChannelDTO c= new ChannelDTO();
          String chid=lblchannelno.getText();
          doctorno=DoctorDao.getidbyName(doctorname.getSelectedItem().toString());
          patientno=PatientDao.getidbyName(jComboBox1.getSelectedItem().toString());
          room=roomno.getValue().toString();
          SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
          date=sdf.format(datechoose.getDate());
          c.setChannel_no(chid);
          c.setDate(date);
          c.setDoctorno(doctorno);
          c.setPatientno(patientno);
          c.setRoomno(room);
          System.out.println("channel obj : "+c);
           // System.out.println("object passed from update function: "+p);
            boolean status=ChannelDao.updateChannel(c);
            System.out.println("worked status..."+status);
            if(status)
            {
                JOptionPane.showMessageDialog(null,"Record UPDATE...","Congrats!!",JOptionPane.INFORMATION_MESSAGE);
                clearAll();
                autoid();
                channelShow();
                addbtn.setEnabled(true);
            }
        }
        catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"Exception in  db while UDATING record\n"+ex,"Error!!",JOptionPane.ERROR_MESSAGE);
            
            Logger.getLogger(ChannelRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_updatebtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
                try {
          ChannelDTO c= new ChannelDTO();
          String chid=lblchannelno.getText();
          doctorno=DoctorDao.getidbyName(doctorname.getSelectedItem().toString());
          patientno=PatientDao.getidbyName(jComboBox1.getSelectedItem().toString());
          room=roomno.getValue().toString();
          SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
          date=sdf.format(datechoose.getDate());
          c.setChannel_no(chid);
          c.setDate(date);
          c.setDoctorno(doctorno);
          c.setPatientno(patientno);
          c.setRoomno(room);
          System.out.println("channel obj : "+c);
            boolean status=ChannelDao.addChannel(c);
            if(status)
            {
                JOptionPane.showMessageDialog(null,"Record inserted...","Congrats!!",JOptionPane.INFORMATION_MESSAGE);
               
                autoid();
                 clearAll();
                channelShow();
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Exception in  db while adding record"+ex,"Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            Logger.getLogger(ChannelRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void channeltableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channeltableMouseClicked
        // TODO add your handling code here:
     
        try {
               DefaultTableModel df=(DefaultTableModel)channeltable.getModel();
        int selectIndex=channeltable.getSelectedRow();
        lblchannelno.setText(df.getValueAt(selectIndex,0).toString());
        doctorname.setSelectedItem(df.getValueAt(selectIndex,1).toString());
        jComboBox1.setSelectedItem(df.getValueAt(selectIndex,2).toString());
        //System.out.println("room: "+df.getValueAt(selectIndex,3).toString());
        roomno.setValue(Integer.parseInt(df.getValueAt(selectIndex,3).toString()));
        String jdate=df.getValueAt(selectIndex,4).toString();
        java.util.Date sd;
            sd = new SimpleDateFormat("yyyy-MM-dd").parse(jdate);
            datechoose.setDate(sd);
            addbtn.setEnabled(false);
        } catch (ParseException ex) {
            Logger.getLogger(ChannelRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    
       
        
        
    }//GEN-LAST:event_channeltableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReceptionalistDashboard r=new ReceptionalistDashboard(username,logid);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChannelRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChannelRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChannelRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChannelRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChannelRegistration().setVisible(true);
            }
        });
    }
    public void channelShow()
    {
      ArrayList<ChannelDTO> al;
        try {
           al = ChannelDao.channelList();
////            for(PatientDTO k:al)
////         {
////             System.out.println(k);
////         }
        if(al.isEmpty()==true)
        {   
            DefaultTableModel df=(DefaultTableModel)channeltable.getModel();//table model is return by get model
            df.setRowCount(0);
            JOptionPane.showMessageDialog(null, "No patient...!","Error!",JOptionPane.INFORMATION_MESSAGE);
             return;
         }
           DefaultTableModel df=(DefaultTableModel)channeltable.getModel();//table model is return by get model
            df.setRowCount(0);//it will delete all the previous row of the table and insert all the new record from database
           Object obj[]=new Object[5];
            for(ChannelDTO c:al)
            {
             obj[0]=c.getChannel_no();
             obj[1]=c.getDoctorno();
             obj[2]=c.getPatientno();
             obj[3]=c.getRoomno();
             obj[4]=c.getDate();
               df.addRow(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChannelRegistration.class.getName()).log(Level.SEVERE, null, ex);
       }
       
        
        
   }
    public void clearAll()
   {
       
   doctorname.setSelectedIndex(-1);
   jComboBox1.setSelectedIndex(-1);
   roomno.setValue(0);
   datechoose.cleanup();
   
      
        
    }
    public void autoid()
    {
        try {
            channelId=ChannelDao.autoIdGenerate();
            lblchannelno.setText(channelId);
        } catch (SQLException ex) {
            Logger.getLogger(ChannelRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTable channeltable;
    private javax.swing.JButton clearallbtn;
    private com.toedter.calendar.JDateChooser datechoose;
    private javax.swing.JButton deletebtn;
    private javax.swing.JComboBox doctorname;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblchannelno;
    private javax.swing.JLabel lblusername;
    private javax.swing.JSpinner roomno;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
