/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronahospital.gui;

/**
 *
 * @author SUDHANSHU YADAV
 */
public class ReceptionalistDashboard extends javax.swing.JFrame {

    /**
     * Creates new form DoctorDashboard
     */
    private static String username;
    private static int logid;
    private static String utype;
    public ReceptionalistDashboard() {
        initComponents();
    }
        public ReceptionalistDashboard(String username,int id,String utype) {
        initComponents();
        this.username=username;
        this.utype=utype;
        logid=id;
        lblusername.setText(username.toUpperCase());
    }
        
        public ReceptionalistDashboard(String username,int id) {
        initComponents();
        this.username=username;
        this.utype=utype;
        logid=id;
        lblusername.setText(username.toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PATIENTREGBTN = new javax.swing.JButton();
        VIEWCHANNELBTN = new javax.swing.JButton();
        CREATECHANNELBTN = new javax.swing.JButton();
        REGISTERUSER = new javax.swing.JButton();
        VIEWDOCTORNBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        PATIENTREGBTN.setText("PATIENT");
        PATIENTREGBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PATIENTREGBTNActionPerformed(evt);
            }
        });

        VIEWCHANNELBTN.setText("VIEW CHANNEL");
        VIEWCHANNELBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWCHANNELBTNActionPerformed(evt);
            }
        });

        CREATECHANNELBTN.setText("CREATE CHANNEL");
        CREATECHANNELBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATECHANNELBTNActionPerformed(evt);
            }
        });

        REGISTERUSER.setText("CREATE USER");
        REGISTERUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERUSERActionPerformed(evt);
            }
        });

        VIEWDOCTORNBTN.setText("VIEW DOCTOR");
        VIEWDOCTORNBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWDOCTORNBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CREATECHANNELBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VIEWCHANNELBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PATIENTREGBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(REGISTERUSER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VIEWDOCTORNBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PATIENTREGBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CREATECHANNELBTN)
                .addGap(14, 14, 14)
                .addComponent(VIEWCHANNELBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(REGISTERUSER)
                .addGap(18, 18, 18)
                .addComponent(VIEWDOCTORNBTN)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(340, 120, 170, 210);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("RECEPTIONALIST DASHBOARD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(133, 21, 370, 28);

        lbllogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(255, 0, 51));
        lbllogout.setText("LOGOUT");
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoutMouseClicked(evt);
            }
        });
        jPanel1.add(lbllogout);
        lbllogout.setBounds(550, 30, 59, 17);

        lblusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblusername.setForeground(new java.awt.Color(51, 255, 51));
        lblusername.setText("USERNAME");
        jPanel1.add(lblusername);
        lblusername.setBounds(10, 30, 80, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\SUDHANSHU YADAV\\Documents\\NetBeansProjects\\CoronaHospital\\src\\Images\\rec.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 120, 200, 230);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PATIENTREGBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PATIENTREGBTNActionPerformed
        // TODO add your handling code here:
        Patient p=new Patient(username,logid);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PATIENTREGBTNActionPerformed

    private void VIEWCHANNELBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWCHANNELBTNActionPerformed
        // TODO add your handling code here:
        ViewChannel v=new ViewChannel(username,logid);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VIEWCHANNELBTNActionPerformed

    private void REGISTERUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERUSERActionPerformed
        // TODO add your handling code here:
        User u=new User(username,logid);
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_REGISTERUSERActionPerformed

    private void CREATECHANNELBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATECHANNELBTNActionPerformed
        // TODO add your handling code here:
        ChannelRegistration c=new ChannelRegistration(username,logid);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CREATECHANNELBTNActionPerformed

    private void VIEWDOCTORNBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWDOCTORNBTNActionPerformed
        // TODO add your handling code here:
        ViewDoctor v=new ViewDoctor(username,logid,utype);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VIEWDOCTORNBTNActionPerformed

    private void lbllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseClicked
        // TODO add your handling code here:
        Login l=new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbllogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionalistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionalistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionalistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionalistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionalistDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CREATECHANNELBTN;
    private javax.swing.JButton PATIENTREGBTN;
    private javax.swing.JButton REGISTERUSER;
    private javax.swing.JButton VIEWCHANNELBTN;
    private javax.swing.JButton VIEWDOCTORNBTN;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblusername;
    // End of variables declaration//GEN-END:variables
}
